image: node:latest

stages:
  - build
  - test
  - integration
cache:
  key: cache_yarn
  paths:
    - .cache_yarn
build:
  stage: build
  script:
    - yarn install
    - yarn run build
  only:
    - master
  artifacts:
    paths:
      - dist
test:
  stage: test
  script:
    - npm run test
